#!/usr/bin/env python3
"""
make_multiaxis_prof.py -- Phase 10.2: write the soft_bus profile of a multi-axis
CiA402 test drive (our own design, vendor 0x499 like soft_bus and P1).

There is no ESI behind this device: it exists to test the master's
multi-axis handling (ETG.6010: axis a uses object index + 0x800 * a) against
the virtual drive (soft_bus --cia402 N:AXES). Regenerate with

    python3 tools/esi/make_multiaxis_prof.py --axes 4 -o config/profiles/cia402_4ax.prof

Per axis a (o = 0x800 * a):
  RxPDO 0x1600+a  0x6040+o:00 16, 0x6060+o:00 8, 0x607A+o:00 32, 0x60FF+o:00 32
  TxPDO 0x1A00+a  0x6041+o:00 16, 0x6061+o:00 8, 0x6064+o:00 32, 0x606C+o:00 32,
                  0x603F+o:00 16
  OD    the PDO objects plus 0x6502 (supported modes: PP PV HM CSP CSV),
        0x6081/0x6083/0x6084/0x6085 (profile), 0x605A (quick stop option),
        0x6065 (following error window), 0x6098/0x6099/0x609A/0x607C (homing)
"""
import argparse
import sys

RX = [(0x6040, 16, "rw"), (0x6060, 8, "rw"), (0x607A, 32, "rw"), (0x60FF, 32, "rw")]
TX = [(0x6041, 16, "ro"), (0x6061, 8, "ro"), (0x6064, 32, "ro"), (0x606C, 32, "ro"), (0x603F, 16, "ro")]
# extra dictionary objects per axis: (index, sub, bits, access, default)
EXTRA = [
    (0x6502, 0, 32, "ro", 0x000001A5),
    (0x6081, 0, 32, "rw", 100000),
    (0x6083, 0, 32, "rw", 1000000),
    (0x6084, 0, 32, "rw", 1000000),
    (0x6085, 0, 32, "rw", 10000000),
    (0x605A, 0, 16, "rw", 2),
    (0x6065, 0, 32, "rw", 0xFFFFFFFF),
    (0x6098, 0, 8, "rw", 37),
    (0x609A, 0, 32, "rw", 1000000),
    (0x607C, 0, 32, "rw", 0),
]


def le(v, bits):
    n = (bits + 7) // 8
    return (v & ((1 << (8 * n)) - 1)).to_bytes(n, "little").hex()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--axes", type=int, default=4)
    ap.add_argument("-o", "--out", default="-")
    a = ap.parse_args()
    if not 1 <= a.axes <= 8:
        sys.exit("--axes 1..8")
    n = a.axes
    rx_bits = sum(b for _, b, _ in RX)
    tx_bits = sum(b for _, b, _ in TX)
    rx_len, tx_len = n * rx_bits // 8, n * tx_bits // 8
    L = []
    w = L.append
    w("# generated by tools/esi/make_multiaxis_prof.py --axes %d -- do not edit, regenerate" % n)
    w("# Phase 10.2 multi-axis CiA402 TEST drive (own design, no ESI): axis a = index + 0x800*a")
    w("profile 1")
    w('name "SOFTBUS-CIA402-%dAX"' % n)
    w("identity vendor 0x00000499 product 0x%08X rev 0x00000001 serial 0x00000000" % (0x0400 + n))
    w("config 0x0080 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000")
    w("mailbox out 0x1000 128 in 0x1080 128 coe 1")
    w("coe sdoinfo 1 pdoassign 1 pdoconfig 0 ca 1")
    w("sm 0 start 0x1000 len 128 ctrl 0x26 en 1")
    w("sm 1 start 0x1080 len 128 ctrl 0x22 en 1")
    w("sm 2 start 0x1100 len %d ctrl 0x64 en 1" % rx_len)
    w("sm 3 start 0x1180 len %d ctrl 0x20 en 1" % tx_len)
    w("dc 1 assign 0x0300")
    for ax in range(n):
        o = 0x800 * ax
        w("pdo rx 0x%04X sm 2 fixed 1 entries %s excludes -" %
          (0x1600 + ax, ",".join("0x%04X:00:%d" % (i + o, b) for i, b, _ in RX)))
    for ax in range(n):
        o = 0x800 * ax
        w("pdo tx 0x%04X sm 3 fixed 1 entries %s excludes -" %
          (0x1A00 + ax, ",".join("0x%04X:00:%d" % (i + o, b) for i, b, _ in TX)))

    def var(idx, bits, acc, val=0):
        w("obj 0x%04X var 1" % idx)
        w("sub 0x%04X 0 bits %d %s %s" % (idx, bits, acc, le(val, bits)))

    var(0x1000, 32, "ro", 0x00020192)
    w("obj 0x1018 record 5")
    w("sub 0x1018 0 bits 8 ro 04")
    w("sub 0x1018 1 bits 32 ro %s" % le(0x499, 32))
    w("sub 0x1018 2 bits 32 ro %s" % le(0x0400 + n, 32))
    w("sub 0x1018 3 bits 32 ro %s" % le(1, 32))
    w("sub 0x1018 4 bits 32 ro %s" % le(0, 32))
    w("obj 0x1C00 array 5")
    w("sub 0x1C00 0 bits 8 ro 04")
    for k, t in enumerate((1, 2, 3, 4), 1):
        w("sub 0x1C00 %d bits 8 ro %02x" % (k, t))
    for obj, base in ((0x1C12, 0x1600), (0x1C13, 0x1A00)):
        w("obj 0x%04X array %d" % (obj, n + 1))
        w("sub 0x%04X 0 bits 8 rw_preop %02x" % (obj, n))
        for ax in range(n):
            w("sub 0x%04X %d bits 16 rw_preop %s" % (obj, ax + 1, le(base + ax, 16)))
    for base, ents in ((0x1600, RX), (0x1A00, TX)):
        for ax in range(n):
            o = 0x800 * ax
            w("obj 0x%04X record %d" % (base + ax, len(ents) + 1))
            w("sub 0x%04X 0 bits 8 ro %02x" % (base + ax, len(ents)))
            for k, (i, b, _) in enumerate(ents, 1):
                w("sub 0x%04X %d bits 32 ro %s" % (base + ax, k, le(((i + o) << 16) | b, 32)))
    for ax in range(n):
        o = 0x800 * ax
        for i, b, acc in RX + TX:
            var(i + o, b, acc)
        for i, s, b, acc, d in EXTRA:
            var(i + o, b, acc, d)
        w("obj 0x%04X record 3" % (0x6099 + o))
        w("sub 0x%04X 0 bits 8 ro 02" % (0x6099 + o))
        w("sub 0x%04X 1 bits 32 rw %s" % (0x6099 + o, le(20000, 32)))
        w("sub 0x%04X 2 bits 32 rw %s" % (0x6099 + o, le(2000, 32)))
    out = "\n".join(L) + "\n"
    if a.out == "-":
        sys.stdout.write(out)
    else:
        open(a.out, "w").write(out)


if __name__ == "__main__":
    main()
