#!/usr/bin/env bash
# ==========================================================================
# import_eni_9_4.sh — Giai doan 9.4: take the ENI files exported by TwinCAT
# (docs/twincat_9_4.md), convert, audit and check them.
#
#   tools/gd9/import_eni_9_4.sh DIR          DIR holds the exported XML files
#   sudo -E RUN=1 tools/gd9/import_eni_9_4.sh DIR   also C-03/C-04 on veth
#
# Expected in DIR (missing ones are reported, not fatal):
#   eni_8node_ca.xml      8 x SOFTBUS-PD4-CA (softbus_esi_ca.xml), DC SYNC0
#   eni_mixed.xml         Box 1 P1-H723-CIA402-DRAFT, Box 2 commercial servo
#   eni_mixed_rev.xml     the same two in the opposite order
#   eni_8node_lrdlwr.xml  8 x SOFTBUS-PD4 with LRD/LWR instead of LRW
#   eni_2servo.xml        2 x Inovance IS620N (GD9.4 C)
#
# Run with sudo (RUN=1) and the files it writes are given back to $SUDO_USER
# (GD9.6: a root-owned config/eni made the next run without sudo fail).
#
# What it does:
#   1. copies them to config/eni/ (keeps a sha256 list)
#   2. eni2cfg.py -> config/eni/*.enicfg; a refusal is a finding (E-07), and
#      its message is kept
#   3. eni_audit.py --known config/eni/known_regs.txt -> docs/eni_audit_9_4.md
#   4. checks: the CA ENI carries CompleteAccess CoE InitCmds; the LRD/LWR ENI
#      is detected as process data by LRD/LWR and the others are not; the
#      mixed ENIs have 2 slaves in opposite order
#   5. RUN=1: tools/gd9/run_coe.sh c03 c04 with the TwinCAT CA ENI
# ==========================================================================
set -u
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/../.." && pwd)
DIR=${1:?usage: import_eni_9_4.sh DIR}
ENI_DIR=$ROOT/config/eni
REPORT=$ROOT/docs/eni_audit_9_4.md
PASS=0; FAIL=0
ok  () { echo "  [PASS] $1"; PASS=$((PASS+1)); }
bad () { echo "  [FAIL] $1"; FAIL=$((FAIL+1)); }
chk () { if eval "$2"; then ok "$1"; else bad "$1"; fi; }

FILES="eni_8node_ca eni_mixed eni_mixed_rev eni_8node_lrdlwr eni_2servo"

# give what this script writes back to the user who ran sudo
give_back () {
    if [ -n "${SUDO_USER:-}" ] && [ "$(id -u)" = 0 ]; then
        chown -R "$SUDO_USER:$(id -gn "$SUDO_USER")" "$ENI_DIR" "$REPORT" 2>/dev/null
        [ -n "${LOG:-}" ] && [ -d "$LOG" ] && chown -R "$SUDO_USER:$(id -gn "$SUDO_USER")" "$LOG" 2>/dev/null
    fi
}
trap give_back EXIT
have=()
echo "=== 1. import from $DIR"
for f in $FILES; do
    if [ -f "$DIR/$f.xml" ]; then
        cp "$DIR/$f.xml" "$ENI_DIR/$f.xml"; have+=("$f")
        echo "    $f.xml  $(sha256sum "$ENI_DIR/$f.xml" | cut -c1-16)"
    else
        echo "    $f.xml  MISSING"
    fi
done
[ ${#have[@]} -gt 0 ] || { echo "nothing to import"; exit 2; }

echo "=== 2. eni2cfg"
declare -A conv
for f in "${have[@]}"; do
    if python3 "$ROOT/tools/eni/eni2cfg.py" "$ENI_DIR/$f.xml" -o "$ENI_DIR/$f.enicfg" > "$ENI_DIR/$f.eni2cfg.log" 2>&1; then
        conv[$f]=1; echo "    $f: converted ($(grep -c '^slave ' "$ENI_DIR/$f.enicfg") slave(s), $(grep -c '^coe ' "$ENI_DIR/$f.enicfg") CoE InitCmd(s))"
    else
        conv[$f]=0; echo "    $f: REFUSED: $(tail -1 "$ENI_DIR/$f.eni2cfg.log")"
    fi
done

echo "=== 3. audit -> ${REPORT#$ROOT/}"
{
    echo "# ENI audit, GD9 step 9.4"
    echo
    echo "Generated by \`tools/gd9/import_eni_9_4.sh\` ($(date +%F)) with \`tools/eni/eni_audit.py --known config/eni/known_regs.txt\`."
    echo "UNKNOWN register InitCmds are the input of the loader table of step 9.6."
    echo
    for f in "${have[@]}"; do
        echo "- \`$f.xml\` sha256 \`$(sha256sum "$ENI_DIR/$f.xml" | cut -c1-16)\`: eni2cfg $([ "${conv[$f]}" = 1 ] && echo converted || echo "**refused**: \`$(tail -1 "$ENI_DIR/$f.eni2cfg.log")\`")"
    done
    echo
    xmls=(); for f in "${have[@]}"; do xmls+=("$ENI_DIR/$f.xml"); done
    python3 "$ROOT/tools/eni/eni_audit.py" --known "$ENI_DIR/known_regs.txt" "${xmls[@]}"
} > "$REPORT" 2>&1
sed -i "s#$ENI_DIR/##g" "$REPORT"
grep -E "^## |UNKNOWN register|not in the known list|process data by" "$REPORT" | sed 's/^/    /'

echo "=== 4. checks"
audit_of () { sed -n "/^## \`$1.xml\`/,/^## \`/p" "$REPORT"; }
for f in "${have[@]}"; do
case $f in
eni_8node_ca)
    chk "CA ENI: converted" "[ ${conv[$f]} = 1 ]"
    chk "CA ENI: has CompleteAccess CoE InitCmds (0x1C12/0x1C13)" \
        "grep -qE '^coe .* index 0x1C1[23] .* ca 1 ' $ENI_DIR/$f.enicfg"
    chk "CA ENI: 8 slaves SOFTBUS-PD4-CA" "[ \$(grep -c 'SOFTBUS-PD4-CA' $ENI_DIR/$f.enicfg) = 8 ]"
    chk "CA ENI: process data by LRW" "audit_of $f | grep -q '(process data by LRW)'"
    ;;
eni_8node_lrdlwr)
    chk "LRD/LWR ENI: detected as process data by LRD/LWR (E-06 input)" \
        "audit_of $f | grep -q 'process data by LRD/LWR'"
    ;;
eni_mixed|eni_mixed_rev)
    if [ "${conv[$f]}" = 1 ]; then
        chk "$f: 2 slaves" "[ \$(grep -c '^slave ' $ENI_DIR/$f.enicfg) = 2 ]"
    else
        ok "$f: refused by eni2cfg with a reason (E-07 finding, see $f.eni2cfg.log)"
    fi
    chk "$f: process data by LRW" "audit_of $f | grep -q '(process data by LRW)'"
    ;;
eni_2servo)
    chk "eni_2servo: 2 slaves, both IS620N (product 0xC0108) with check_rev 1" \
        "[ \$(grep -c '^slave .* product 0xC0108 .* check_rev 1 ' $ENI_DIR/$f.enicfg) = 2 ]"
    chk "eni_2servo: process data by LRW" "audit_of $f | grep -q '(process data by LRW)'"
    ;;
esac
done
if [ -f "$ENI_DIR/eni_mixed.enicfg" ] && [ -f "$ENI_DIR/eni_mixed_rev.enicfg" ]; then
    v1=$(grep '^slave 1 ' "$ENI_DIR/eni_mixed.enicfg" | grep -oE 'product 0x[0-9A-Fa-f]+')
    v2=$(grep '^slave 2 ' "$ENI_DIR/eni_mixed_rev.enicfg" | grep -oE 'product 0x[0-9A-Fa-f]+')
    chk "mixed vs mixed_rev: slave 1 of one is slave 2 of the other ($v1)" "[ -n '$v1' ] && [ '$v1' = '$v2' ]"
fi

if [ "${RUN:-0}" = 1 ] && [ "${conv[eni_8node_ca]:-0}" = 1 ]; then
    echo "=== 5. C-03 / C-04 with the TwinCAT CA ENI"
    ENI_CA=$ENI_DIR/eni_8node_ca.enicfg CASES="c03 c04" "$HERE/run_coe.sh" | sed 's/^/    /'
    [ "${PIPESTATUS[0]}" = 0 ] && ok "C-03/C-04 with eni_8node_ca" || bad "C-03/C-04 with eni_8node_ca"
fi
echo "RESULT: $PASS pass, $FAIL fail   (report: ${REPORT#$ROOT/})"
[ "$FAIL" = 0 ]
