/*
 * test_eni_offline.c -- ecm_eni loader and checks, no SOEM, no network.
 * Run from the repo root:  libecmaster/config/test_eni_offline
 * (reads the .enicfg files in config/eni/ generated by tools/eni/eni2cfg.py)
 */
#include "ecm_eni.h"

#include <stdio.h>
#include <string.h>

static int npass, nfail;

static void check(const char *what, int ok)
{
    printf("  [%s] %s\n", ok ? "PASS" : "FAIL", what);
    if (ok) npass++; else nfail++;
}

static ecm_eni_t eni;          /* large: keep off the stack */
static char err[4096];

static void fill_found(ecm_eni_found_t *f, int n)
{
    for (int i = 0; i < n; i++) {
        f[i].vendor = 0x499; f[i].product = 1; f[i].rev = 1;
        f[i].obits = 32; f[i].ibits = 32;
    }
}

static int expect_parse_error(const char *text, const char *needle)
{
    ecm_eni_t *e = &eni;
    int rc = ecm_eni_parse_text(text, e, err, sizeof(err));
    return rc != 0 && strstr(err, needle) != NULL;
}

int main(void)
{
    ecm_eni_found_t found[ECM_ENI_MAX_SLAVES];

    printf("[load eni_1node_1pdo.enicfg]\n");
    int rc = ecm_eni_load("config/eni/eni_1node_1pdo.enicfg", &eni, err, sizeof(err));
    if (rc) printf("    %s\n", err);
    check("loads", rc == 0);
    check("1 slave, cycle 1000 us", eni.nslaves == 1 && eni.cycle_us == 1000);
    check("addr 0x03E9 (TwinCAT decimal 1001)", eni.slave[0].addr == 0x03E9);
    check("no DC, no CoE, rev not checked",
          !eni.slave[0].dc && eni.ncoe == 0 && !eni.slave[0].check_rev);

    printf("[load eni_8node_dc_sdo.enicfg]\n");
    rc = ecm_eni_load("config/eni/eni_8node_dc_sdo.enicfg", &eni, err, sizeof(err));
    if (rc) printf("    %s\n", err);
    check("loads", rc == 0);
    check("8 slaves, positions 1..8", eni.nslaves == 8 && eni.slave[7].pos == 8);
    check("refclock = position 1", ecm_eni_refclock(&eni) == 1);
    check("DC sync0 1 ms, assign 0x0300 on all",
          eni.slave[4].dc && eni.slave[4].sync0_ns == 1000000 && eni.slave[4].assign == 0x0300);
    check("one CoE InitCmd: PS download 0x8000:01 = 2a000000",
          eni.ncoe == 1 && eni.coe[0].pos == 1 && eni.coe[0].trans == ECM_ENI_T_PS &&
          eni.coe[0].ccs == ECM_ENI_CCS_DOWNLOAD && eni.coe[0].index == 0x8000 &&
          eni.coe[0].sub == 1 && eni.coe[0].len == 4 && eni.coe[0].data[0] == 0x2a);

    printf("[identity check, E-03]\n");
    fill_found(found, 8);
    check("matching bus -> 0 mismatches", ecm_eni_check_identity(&eni, 8, found, err, sizeof(err)) == 0);
    check("7 slaves on bus -> rejected", ecm_eni_check_identity(&eni, 7, found, err, sizeof(err)) == 1 &&
                                          strstr(err, "ENI 8, bus 7"));
    fill_found(found, 8);
    found[4].product = 2;
    rc = ecm_eni_check_identity(&eni, 8, found, err, sizeof(err));
    check("wrong product at position 5 -> named", rc == 1 && strstr(err, "position 5"));
    fill_found(found, 8);
    found[2].rev = 2;
    rc = ecm_eni_check_identity(&eni, 8, found, err, sizeof(err));
    check("wrong revision at position 3 (check_rev 1) -> named", rc == 1 && strstr(err, "position 3"));

    printf("[revision not checked when the ENI does not ask]\n");
    ecm_eni_load("config/eni/eni_1node_1pdo.enicfg", &eni, err, sizeof(err));
    fill_found(found, 1);
    found[0].rev = 7;
    check("1node ENI (check_rev 0) accepts rev 7",
          ecm_eni_check_identity(&eni, 1, found, err, sizeof(err)) == 0);

    printf("[layout check]\n");
    ecm_eni_load("config/eni/eni_8node.enicfg", &eni, err, sizeof(err));
    fill_found(found, 8);
    check("32/32 bits everywhere -> OK", ecm_eni_check_layout(&eni, 8, found, err, sizeof(err)) == 0);
    found[6].ibits = 64;
    check("position 7 mapped 64 in bits -> named",
          ecm_eni_check_layout(&eni, 8, found, err, sizeof(err)) == 1 && strstr(err, "position 7"));

    printf("[strict parser]\n");
    check("missing header", expect_parse_error("slaves 1\n", "enicfg 1"));
    check("unknown record", expect_parse_error("enicfg 1\nfoo 1\n", "unknown record"));
    check("count mismatch", expect_parse_error("enicfg 1\nslaves 2\n", "'slaves 2' but 0"));
    const char *s1 =
        "enicfg 1\nslaves 1\n"
        "slave 1 name \"a b\" vendor 0x499 product 0x1 rev 0x1 check_rev 1 addr 0x03E9 "
        "osize_bits 32 isize_bits 32 dc 0 refclock 0 sync0_ns 0 sync1_ns 0 shift_ns 0 assign 0x0000\n";
    check("quoted name with space parses", ecm_eni_parse_text(s1, &eni, err, sizeof(err)) == 0 &&
                                           strcmp(eni.slave[0].name, "a b") == 0);
    char buf[1024];
    snprintf(buf, sizeof(buf), "%scoe 1 trans XX ccs 1 index 0x8000 sub 1 ca 0 timeout_ms 0 data 00\n", s1);
    check("bad transition", expect_parse_error(buf, "bad 'trans'"));
    snprintf(buf, sizeof(buf), "%scoe 2 trans PS ccs 1 index 0x8000 sub 1 ca 0 timeout_ms 0 data 00\n", s1);
    check("coe for undeclared slave", expect_parse_error(buf, "not a declared slave"));
    snprintf(buf, sizeof(buf), "%scoe 1 trans PS ccs 1 index 0x8000 sub 1 ca 0 timeout_ms 0 data -\n", s1);
    check("download without data", expect_parse_error(buf, "download without data"));
    snprintf(buf, sizeof(buf), "%scoe 1 trans PS ccs 1 index 0x8000 sub 1 ca 0 timeout_ms 0 data 2a0\n", s1);
    check("odd hex", expect_parse_error(buf, "bad 'data'"));
    check("slave missing field",
          expect_parse_error("enicfg 1\nslaves 1\nslave 1 vendor 0x499\n", "missing 'product'"));
    check("trans list IP,PS -> 2 bits", ecm_eni_trans_parse("IP,PS") == (ECM_ENI_T_IP | ECM_ENI_T_PS));

    printf("\nRESULT: %d pass, %d fail\n", npass, nfail);
    return nfail ? 1 : 0;
}
