/*
 * test_eni_offline.c -- ecm_eni loader and checks, no SOEM, no network.
 * Run from the repo root:  libecmaster/config/test_eni_offline
 * (reads the .enicfg files in config/eni/ generated by tools/eni/eni2cfg.py)
 */
#include "ecm_eni.h"

#include <stdio.h>
#include <string.h>

static int npass, nfail;

static void check(const char *what, int ok)
{
    printf("  [%s] %s\n", ok ? "PASS" : "FAIL", what);
    if (ok) npass++; else nfail++;
}

static ecm_eni_t eni;          /* large: keep off the stack */
static char err[4096];

static void fill_found(ecm_eni_found_t *f, int n)
{
    for (int i = 0; i < n; i++) {
        f[i].vendor = 0x499; f[i].product = 1; f[i].rev = 1;
        f[i].obits = 32; f[i].ibits = 32;
    }
}

static int expect_parse_error(const char *text, const char *needle)
{
    ecm_eni_t *e = &eni;
    int rc = ecm_eni_parse_text(text, e, err, sizeof(err));
    return rc != 0 && strstr(err, needle) != NULL;
}

int main(void)
{
    ecm_eni_found_t found[ECM_ENI_MAX_SLAVES];

    printf("[load eni_1node_1pdo.enicfg]\n");
    int rc = ecm_eni_load("config/eni/eni_1node_1pdo.enicfg", &eni, err, sizeof(err));
    if (rc) printf("    %s\n", err);
    check("loads", rc == 0);
    check("1 slave, cycle 1000 us", eni.nslaves == 1 && eni.cycle_us == 1000);
    check("addr 0x03E9 (TwinCAT decimal 1001)", eni.slave[0].addr == 0x03E9);
    check("no DC, no CoE, rev not checked",
          !eni.slave[0].dc && eni.ncoe == 0 && !eni.slave[0].check_rev);

    printf("[load eni_8node_dc_sdo.enicfg]\n");
    rc = ecm_eni_load("config/eni/eni_8node_dc_sdo.enicfg", &eni, err, sizeof(err));
    if (rc) printf("    %s\n", err);
    check("loads", rc == 0);
    check("8 slaves, positions 1..8", eni.nslaves == 8 && eni.slave[7].pos == 8);
    check("refclock = position 1", ecm_eni_refclock(&eni) == 1);
    check("DC sync0 1 ms, assign 0x0300 on all",
          eni.slave[4].dc && eni.slave[4].sync0_ns == 1000000 && eni.slave[4].assign == 0x0300);
    check("one CoE InitCmd: PS download 0x8000:01 = 2a000000",
          eni.ncoe == 1 && eni.coe[0].pos == 1 && eni.coe[0].trans == ECM_ENI_T_PS &&
          eni.coe[0].ccs == ECM_ENI_CCS_DOWNLOAD && eni.coe[0].index == 0x8000 &&
          eni.coe[0].sub == 1 && eni.coe[0].len == 4 && eni.coe[0].data[0] == 0x2a);

    printf("[identity check, E-03]\n");
    fill_found(found, 8);
    check("matching bus -> 0 mismatches", ecm_eni_check_identity(&eni, 8, found, err, sizeof(err)) == 0);
    check("7 slaves on bus -> rejected", ecm_eni_check_identity(&eni, 7, found, err, sizeof(err)) == 1 &&
                                          strstr(err, "ENI 8, bus 7"));
    fill_found(found, 8);
    found[4].product = 2;
    rc = ecm_eni_check_identity(&eni, 8, found, err, sizeof(err));
    check("wrong product at position 5 -> named", rc == 1 && strstr(err, "position 5"));
    fill_found(found, 8);
    found[2].rev = 2;
    rc = ecm_eni_check_identity(&eni, 8, found, err, sizeof(err));
    check("wrong revision at position 3 (check_rev 1) -> named", rc == 1 && strstr(err, "position 3"));

    printf("[revision not checked when the ENI does not ask]\n");
    ecm_eni_load("config/eni/eni_1node_1pdo.enicfg", &eni, err, sizeof(err));
    fill_found(found, 1);
    found[0].rev = 7;
    check("1node ENI (check_rev 0) accepts rev 7",
          ecm_eni_check_identity(&eni, 1, found, err, sizeof(err)) == 0);

    printf("[layout check]\n");
    ecm_eni_load("config/eni/eni_8node.enicfg", &eni, err, sizeof(err));
    fill_found(found, 8);
    check("32/32 bits everywhere -> OK", ecm_eni_check_layout(&eni, 8, found, err, sizeof(err)) == 0);
    found[6].ibits = 64;
    check("position 7 mapped 64 in bits -> named",
          ecm_eni_check_layout(&eni, 8, found, err, sizeof(err)) == 1 && strstr(err, "position 7"));

    printf("[strict parser]\n");
    check("missing header", expect_parse_error("slaves 1\n", "enicfg 1"));
    check("unknown record", expect_parse_error("enicfg 1\nfoo 1\n", "unknown record"));
    check("count mismatch", expect_parse_error("enicfg 1\nslaves 2\n", "'slaves 2' but 0"));
    const char *s1 =
        "enicfg 1\nslaves 1\n"
        "slave 1 name \"a b\" vendor 0x499 product 0x1 rev 0x1 check_rev 1 addr 0x03E9 "
        "osize_bits 32 isize_bits 32 dc 0 refclock 0 sync0_ns 0 sync1_ns 0 shift_ns 0 assign 0x0000\n";
    check("quoted name with space parses", ecm_eni_parse_text(s1, &eni, err, sizeof(err)) == 0 &&
                                           strcmp(eni.slave[0].name, "a b") == 0);
    char buf[2048];
    snprintf(buf, sizeof(buf), "%scoe 1 trans XX ccs 1 index 0x8000 sub 1 ca 0 timeout_ms 0 data 00\n", s1);
    check("bad transition", expect_parse_error(buf, "bad 'trans'"));
    snprintf(buf, sizeof(buf), "%scoe 2 trans PS ccs 1 index 0x8000 sub 1 ca 0 timeout_ms 0 data 00\n", s1);
    check("coe for undeclared slave", expect_parse_error(buf, "not a declared slave"));
    snprintf(buf, sizeof(buf), "%scoe 1 trans PS ccs 1 index 0x8000 sub 1 ca 0 timeout_ms 0 data -\n", s1);
    check("download without data", expect_parse_error(buf, "download without data"));
    snprintf(buf, sizeof(buf), "%scoe 1 trans PS ccs 1 index 0x8000 sub 1 ca 0 timeout_ms 0 data 2a0\n", s1);
    check("odd hex", expect_parse_error(buf, "bad 'data'"));
    check("slave missing field",
          expect_parse_error("enicfg 1\nslaves 1\nslave 1 vendor 0x499\n", "missing 'product'"));
    check("trans list IP,PS -> 2 bits", ecm_eni_trans_parse("IP,PS") == (ECM_ENI_T_IP | ECM_ENI_T_PS));

    /* ------------------------------------------------------------ Phase 9.6 */
    printf("[Phase 9.6: every committed ENI loads as enicfg 2]\n");
    static const char *const v2[] = { "eni_1node_1pdo", "eni_8node", "eni_8node_dc", "eni_8node_dc_sdo",
                                      "eni_8node_ca", "eni_mixed", "eni_mixed_rev", "eni_2servo" };
    for (size_t i = 0; i < sizeof(v2) / sizeof(v2[0]); i++) {
        char path[128], what[160];
        snprintf(path, sizeof(path), "config/eni/%s.enicfg", v2[i]);
        rc = ecm_eni_load(path, &eni, err, sizeof(err));
        int warn = -1;
        int bad = rc ? -1 : ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err));
        snprintf(what, sizeof(what), "%s: enicfg 2, LRW, %d register InitCmds all known", v2[i], eni.nreg);
        if (bad) printf("    %s\n", err);
        check(what, rc == 0 && eni.version == 2 && eni.pd_cmd == ECM_ENI_PD_LRW && eni.nreg > 0 &&
                    bad == 0 && warn == 0);
    }

    printf("[E-06 offline: LRD/LWR ENI refused]\n");
    rc = ecm_eni_load("config/eni/eni_8node_lrdlwr.enicfg", &eni, err, sizeof(err));
    check("eni_8node_lrdlwr loads, pd_cmd lrd_lwr", rc == 0 && eni.pd_cmd == ECM_ENI_PD_LRD_LWR);
    int warn = 0;
    rc = ecm_eni_check_supported(&eni, 1, &warn, err, sizeof(err));
    check("refused even with --eni-allow-unknown-regcmd, message names LRW",
          rc == 1 && strstr(err, "LRD/LWR not supported, use LRW"));

    printf("[state timeouts from the AL Control InitCmds]\n");
    ecm_eni_load("config/eni/eni_2servo.enicfg", &eni, err, sizeof(err));
    check("IS620N: PREOP 3000, SAFEOP 9000, OP 9000 ms (ESI timeouts)",
          eni.slave[1].state_ms[ECM_ENI_ST_PREOP] == 3000 && eni.slave[1].state_ms[ECM_ENI_ST_SAFEOP] == 9000 &&
          eni.slave[1].state_ms[ECM_ENI_ST_OP] == 9000);
    ecm_eni_load("config/eni/eni_mixed_rev.enicfg", &eni, err, sizeof(err));
    check("mixed_rev: bus timeout = longest slave (SAFEOP 10000 from P1 draft)",
          ecm_eni_state_timeout_ms(&eni, ECM_ENI_ST_SAFEOP) == 10000 &&
          eni.slave[0].state_ms[ECM_ENI_ST_SAFEOP] == 9000);
    check("mixed_rev: ref clock is slave 1 (IS620N)", ecm_eni_refclock(&eni) == 1);

    printf("[E-08 offline: unknown register InitCmd]\n");
    const char *s2 =
        "enicfg 2\npd_cmd lrw\nslaves 1\n"
        "slave 1 name \"a\" vendor 0x499 product 0x1 rev 0x1 check_rev 1 addr 0x03E9 "
        "osize_bits 32 isize_bits 32 dc 0 refclock 0 sync0_ns 0 sync1_ns 0 shift_ns 0 assign 0x0000 "
        "preop_ms 3000 safeop_ms 10000 op_ms 10000\n"
        "reg 0 trans IP cmd 8 ado 0x0800 len 0 data -\n"
        "reg 1 trans IP,IB cmd 5 ado 0x0010 len 2 data e903\n";
    rc = ecm_eni_parse_text(s2, &eni, err, sizeof(err));
    check("known-only enicfg 2 parses", rc == 0 && eni.nreg == 2);
    check("... and is accepted", ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err)) == 0 && warn == 0);
    snprintf(buf, sizeof(buf), "%sreg 1 trans PS cmd 5 ado 0x0420 len 2 data e803\n", s2);
    ecm_eni_parse_text(buf, &eni, err, sizeof(err));
    rc = ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err));
    check("0x0420 (watchdog) refused, line names slave, transition, cmd, ADO, data",
          rc == 1 && strstr(err, "slave 1 register InitCmd PS FPWR 0x0420 len 2 data e803"));
    rc = ecm_eni_check_supported(&eni, 1, &warn, err, sizeof(err));
    check("--eni-allow-unknown-regcmd: 0 refusals, 1 warning",
          rc == 0 && warn == 1 && strstr(err, "warning: slave 1"));
    snprintf(buf, sizeof(buf), "%sreg 1 trans PS cmd 5 ado 0x09A8 len 2 data 0000\n", s2);
    ecm_eni_parse_text(buf, &eni, err, sizeof(err));
    check("0x09A8 latch = 0 is known", ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err)) == 0);
    snprintf(buf, sizeof(buf), "%sreg 1 trans PS cmd 5 ado 0x09A8 len 2 data 0300\n", s2);
    ecm_eni_parse_text(buf, &eni, err, sizeof(err));
    check("0x09A8 latch enabled is refused", ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err)) == 1 &&
                                             strstr(err, "non-zero"));
    snprintf(buf, sizeof(buf), "%sreg 1 trans PS cmd 3 ado 0x0120 len 2 data 0400\n", s2);
    ecm_eni_parse_text(buf, &eni, err, sizeof(err));
    check("known ADO with an RW command is refused",
          ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err)) == 1 && strstr(err, "APRW"));
    snprintf(buf, sizeof(buf), "%sreg 1 trans PS cmd 5 ado 0x0F00 len 40 "
             "data 0102030405060708091011121314151617181920212223242526272829303132\n", s2);
    ecm_eni_parse_text(buf, &eni, err, sizeof(err));
    check("long data printed truncated with '..'",
          ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err)) == 1 && strstr(err, "32..: "));

    printf("[Phase 9.6 parser]\n");
    check("enicfg 2 without pd_cmd",
          expect_parse_error("enicfg 2\nslaves 1\nslave 1 vendor 0x1 product 0x1 rev 0x1 check_rev 0 addr 1 "
                             "osize_bits 0 isize_bits 0 dc 0 refclock 0 sync0_ns 0 sync1_ns 0 shift_ns 0 assign 0\n",
                             "without a 'pd_cmd'"));
    snprintf(buf, sizeof(buf), "%sreg 1 trans PS cmd 5 ado 0x0420 len 2 data e803\n", s1);
    check("reg record in an enicfg 1 file is unknown", expect_parse_error(buf, "unknown record 'reg'"));
    ecm_eni_parse_text(s1, &eni, err, sizeof(err));
    rc = ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err));
    check("enicfg 1 still accepted, with a 'not checked' warning",
          eni.version == 1 && rc == 0 && warn == 1 && strstr(err, "not checked"));
    snprintf(buf, sizeof(buf), "%sreg 2 trans PS cmd 5 ado 0x0010 len 2 data 0000\n", s2);
    check("reg for undeclared slave", expect_parse_error(buf, "not 0 (master) or a declared slave"));
    check("transition OP (OP -> PREOP) parses",
          ecm_eni_trans_parse("SP,OP") == (ECM_ENI_T_SP | ECM_ENI_T_OP));

    /* ------------------------------------------------------------ Phase 9.5 */
    printf("[Phase 9.5: DC register InitCmds agree with the DC element]\n");
    const char *s3 =
        "enicfg 2\npd_cmd lrw\nslaves 1\n"
        "slave 1 name \"a\" vendor 0x499 product 0x1 rev 0x1 check_rev 1 addr 0x03E9 "
        "osize_bits 32 isize_bits 32 dc 1 refclock 1 sync0_ns 1000000 sync1_ns 0 shift_ns 0 assign 0x0300\n"
        "reg 1 trans PS cmd 5 ado 0x0980 len 2 data 0003\n";
    snprintf(buf, sizeof(buf), "%sreg 1 trans PS cmd 5 ado 0x09A0 len 8 data 40420f0000000000\n", s3);
    rc = ecm_eni_parse_text(buf, &eni, err, sizeof(err));
    check("coherent DC InitCmds accepted", rc == 0 && ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err)) == 0);
    snprintf(buf, sizeof(buf), "%sreg 1 trans PS cmd 5 ado 0x09A0 len 8 data 40420f00400d0300\n", s3);
    ecm_eni_parse_text(buf, &eni, err, sizeof(err));
    rc = ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err));
    check("0x09A0 write with SYNC1 200000 vs DC element 0 -> refused, names 0x09A4",
          rc == 1 && strstr(err, "slave 1: DC register InitCmd 0x09A4") && strstr(err, "writes 200000"));
    snprintf(buf, sizeof(buf), "%sreg 1 trans PS cmd 5 ado 0x09A0 len 4 data 20a10700\n", s3);
    ecm_eni_parse_text(buf, &eni, err, sizeof(err));
    check("0x09A0 = 500000 vs sync0 1000000 -> refused",
          ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err)) == 1 && strstr(err, "0x09A0"));
    snprintf(buf, sizeof(buf), "%sreg 1 trans PS cmd 5 ado 0x0980 len 2 data 0007\n", s3);
    ecm_eni_parse_text(buf, &eni, err, sizeof(err));
    check("second 0x0980 write 0x0700 vs assign 0x0300 -> refused",
          ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err)) == 1 && strstr(err, "AssignActivate"));
    snprintf(buf, sizeof(buf), "%sreg 1 trans SP cmd 5 ado 0x0980 len 2 data 0000\n", s3);
    ecm_eni_parse_text(buf, &eni, err, sizeof(err));
    check("SP 'clear DC activation' (0x0980 = 0) is not compared",
          ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err)) == 0);
    snprintf(buf, sizeof(buf), "%sreg 1 trans PS cmd 5 ado 0x09A4 len 4 data 400d0300\n", s3);
    ecm_eni_parse_text(buf, &eni, err, sizeof(err));
    check("separate 0x09A4 write vs sync1 0 -> refused",
          ecm_eni_check_supported(&eni, 0, &warn, err, sizeof(err)) == 1 && strstr(err, "SYNC1 cycle"));

    /* ------------------------------------------------------------ Phase 9.10 */
    printf("[Phase 9.10: PDO entries from the ENI]\n");
    rc = ecm_eni_load("config/eni/eni_mixed.enicfg", &eni, err, sizeof(err));
    check("eni_mixed: 27 PDO entries", rc == 0 && eni.npdo == 27);
    check("P1 first output 0x6040:00 16 bit in PDO 0x1600",
          eni.pdo[0].pos == 1 && !eni.pdo[0].dir && eni.pdo[0].pdo == 0x1600 && eni.pdo[0].index == 0x6040 &&
          eni.pdo[0].bits == 16);
    check("P1 inputs: 0x1A00 before 0x1A01 (order of the 0x1C13 CA InitCmd)",
          eni.pdo[11].pdo == 0x1A01 && eni.pdo[10].pdo == 0x1A00 && eni.pdo[11].index == 0x2F00);
    check("IS620N outputs from 0x1701 (assigned by the non-CA InitCmds)",
          eni.pdo[14].pos == 2 && eni.pdo[14].pdo == 0x1701 && eni.pdo[17].index == 0x60FE && eni.pdo[17].sub == 1);
    snprintf(buf, sizeof(buf), "%s%s", s2, "pdo 1 dir out pdo 0x1600 index 0x7000 sub 0x01 bits 16\n");
    check("pdo entries not adding up to the slave size -> refused",
          expect_parse_error(buf, "slave 1: pdo entries 16 out / 0 in bits, slave record 32 / 32"));
    snprintf(buf, sizeof(buf), "%s%s", s2, "pdo 1 dir up pdo 0x1600 index 0x7000 sub 0x01 bits 32\n");
    check("bad dir -> refused", expect_parse_error(buf, "pdo: bad 'dir'"));

    printf("\nRESULT: %d pass, %d fail\n", npass, nfail);
    return nfail ? 1 : 0;
}
